#!/bin/sh
set -e

DBLAUNCH_CONF=$HOME/.config/dblaunch/dblaunch.conf

die() {
    kdialog --error "$*"
    exit 1
}

if [ ! -f $DBLAUNCH_CONF ] ; then
    die "$DBLAUNCH_CONF does not exist."
fi

. $DBLAUNCH_CONF

if [ -z "$DOS_BASE_DIR" ] ; then
    die "\$DOS_BASE_DIR not set in $DBLAUNCH_CONF."
fi

cd $DOS_BASE_DIR
for desktop_name in *.desktop ; do
    name=$(basename $desktop_name .desktop)
    echo "Installing desktop file for $name"
    cp $desktop_name ~/.local/share/applications/
    iconinstaller --vendor dblaunch $name.png $name
done
